[project]
name = "btc-reputation-lending"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/btc-reputation-lending/btc-reputation-lending/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.btc-reputation-lending]
path = "contracts/btc-reputation-lending.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
